### ISSUE TITLE
stripColorsAndStyle doesn't seem to strip correctly

### ISSUE THREAD

**Issue by Throne3d** [fent/irc-colors.js#12] opened 2017-03-25 17:34 UTC
I was experiencing an error when producing tests for a program that used this package, and it didn't seem to make sense. When I tried the same data in a test for `stripColorsAndStyle`, it didn't seem to produce accurate results with test data `ircColors.rainbow('rainbow')`.

```
console.log(ircColors.stripColors(ircColors.rainbow('rainbow')));
console.log(ircColors.stripColorsAndStyle(ircColors.rainbow('rainbow')));
```

produces:

```
rainbow
rainbow
```

 (i.e. `ircColors.stripColorsAndStyle(ircColors.rainbow('rainbow')) !== 'rainbow'`.)

I copied the test data given for the `rainbow` function, in the vows testing, into the `stripColors` and `stripColorsAndStyle` vows (but reverse), and only the first seems to pass. I don't think I'm doing something silly here – stripping the colors and style from a piece of rainbowed text should produce the original text, just as stripping only the colors would?

Modified tests for the vows:

```
'stripColors': [
  '\x0304' + zero + 'h\x03\x0307' + zero + 'e\x03\x0308' + zero +
  'l\x03\x0303' + zero + 'l\x03\x0312' + zero + 'o\x03 \x0302' + zero +
  'u\x03',
  'hello u'
],
'stripColorsAndStyle': [
  '\x0304' + zero + 'h\x03\x0307' + zero + 'e\x03\x0308' + zero +
  'l\x03\x0303' + zero + 'l\x03\x0312' + zero + 'o\x03 \x0302' + zero +
  'u\x03',
  'hello u'
]
```

Error produced:

```
    ✓ stripColors
    …
    ✗ stripColorsAndStyle 
        » expected { 
      0: 104, 
      1: 101, 
      2: 108, 
      3: 108, 
      4: 111, 
      5: 32, 
      6: 117 
  }, 
  	got	 { 
      0: 2, 
      1: 104, 
      2: 101, 
      3: 108, 
      4: 108, 
      5: 111, 
      6: 32, 
      7: 2, 
      8: 117 
  } (deepEqual) // /home/throne3d/irc-colors.js/test/main-test.js:106
```

This appears in both regular and global syntax.

Another problem, possibly related, happens with nested styling. For example,
```
console.log(ircColors.stripStyle(ircColors.bold(`bold text, ${ircColors.italic('italic and bold text')}`)));
```
produces:
```
bold text, italic and bold text
```

Am I missing something?

**Comment by rahatarmanahmed** [comment] 2017-03-25 21:38
Seems to be a regression in this commit: https://github.com/fent/irc-colors.js/commit/5e0470602c6ac9a9565f8ef49f0d2e4bf18ced73#diff-ceb89046277e7d24d20549515fa66774R86

I think it can probably be fixed if you switch the order you call stripStyles and stripColors in stripColorsAndStyle.

**Comment by rahatarmanahmed** [comment] 2017-03-25 21:51
OK yeah, confirmed that does fix the issue. But I have other concerns about using `\x02\x02` as a zero width separator for colors? The commit I linked above changed the stripping code so that it only strips styles that have matching start and end control characters. If a string starts with a bold `\x02` marker but doesn't put a "closing" `\x02` marker somewhere to mark the end of the bold range, it won't strip that, even though that's a valid way to bold the text up to the end of the string. It also won't strip styles that are terminated with the normal `\x0F` marker.

```
> var c = require('./')
> c.stripStyle('\x02wow\x02')
'wow'
> c.stripStyle('\x02wow\x0F')
'\u0002wow\u000f'
> c.stripStyle('\x02wow')
'\u0002wow'
```

**Closed** 2017-03-27 23:40 UTC
